# Frontend deployment
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: egs-docmanager
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.deti/egs-docmanager/frontend:1.2
        ports:
        - containerPort: 3000


# Frontend service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: egs-docmanager
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend

