apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pv-claim
  namespace: egs-docmanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
