# Use postgres/example user/password credentials
version: '3.9'

services:

  meetings_db:
    container_name: meetings_db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  meetings-docs-api:
    image: meetings-docs-api 
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:example@meetings_db:5432/postgres
    ports:
      - "80:80"
    depends_on:
      - meetings_db
