version: "3.9"

services:
  todo_api:
    build: .
    container_name: "todo_api"
    ports:
      - '8002:8002'
    depends_on:
      - todo-db
    environment:
      - DATABASE_URL=mysql://docker:docker@todo-db:3306/exampledb

  todo-db:
    image: mysql
    container_name: "todo-db"
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: exampledb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - db_photo_upload_service:/var/lib/mysql

volumes:
  db_photo_upload_service:  
