version: '3.9'

services:
  db:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  api:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:password@db:3306/auth"

volumes:
  db_data:
